import string
import secrets

characters = string.ascii_uppercase + string.ascii_lowercase + string.digits + string.punctuation

while True :
    print("Welcome to the Strong Password Generator. Please answer the below questions for suitable random password. Your Password will be 20 characters.")
    
    print("Specify the minimum number of capital letters:")
    capital_characters = int(input())
    
    print("Specify the minimum number of lowercase letters:")
    lowercase_characters = int(input())
    
    print("Specify the minimum number of numbers:")
    number_characters = int(input())
    
    print("Specify the minimum number of special characters:")
    special_characters = int(input())
    
    sum_characters = capital_characters + lowercase_characters + number_characters + special_characters
    
    if sum_characters <= 20:
        while True:
            password = ''.join(secrets.choice(characters) for i in range(20))
            if (sum(c.isupper() for c in password) >= capital_characters and sum(c.islower() for c in password) >= lowercase_characters and sum(c.isdigit() for c in password) >= number_characters and sum(c in string.punctuation for c in password) >= special_characters) :
                break
        print(password)
    else:
        print("The total number of selected characters is more than the maximum number of passwords that can be generated by the program.")